name: CratesPlus
description: A free and great crates plugin for Minecraft
main: plus.crates.CratesPlus
version: ${project.version}
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus,crates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op